version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: duarte_performance_db
    restart: always
    environment:
      POSTGRES_USER: duarte_admin
      POSTGRES_PASSWORD: duarte_senha_secreta
      POSTGRES_DB: duarte_performance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: